server:
  port: 8080
  address: 127.0.0.1
logging:
  level:
    root: DEBUG
spring:
  application:
    name: 卡管家平台管理系统
  profiles:
    active: dev
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
---
spring:
  profiles: product
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.89.34.17:3306/ccmanager?useUnicode=true&characterEncoding=utf-8
    username: shuo
    password: Cs!MySQL321368
---
spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.89.34.17:3306/ccmanager?useUnicode=true&characterEncoding=utf-8
    username: shuo
    password: Cs!MySQL321368