server:
  port: 8080
  address: 127.0.0.1
spring:
  application:
    name: 卡管家平台管理系统
  profiles:
    active: product
  jmx:
    default-domain: ccmanager666
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
      schema: classpath:quartz.sql
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            class : org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass : org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties : false
            tablePrefix : A_QRTZ_
            isClustered : false
---
spring:
  profiles: product
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.winsyo.com:3306/shiro?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wzy@2017.remote
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
---
spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.89.34.17:3306/ccmanager?useUnicode=true&characterEncoding=utf-8
    username: shuo
    password: Cs!MySQL321368
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect