server:
  port: 8080
  address: 127.0.0.1
spring:
  application:
    name: 分销系统
  profiles:
    active: dev
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
security:
  user:
    name: admin
    password: admin

---
spring:
  profiles: product
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.89.34.17:3306/distribution
    username: shuo
    password: Cs!MySQL321368
---
spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.89.34.17:3306/distribution
    username: shuo
    password: Cs!MySQL321368